[package]
name = "notify-tg"
version = "1.0.0"
authors = ["Mr-Andersen <andrew-anderson.neo@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
dirs = "2.0"
log = "0.4"
pretty_env_logger = "0.4"
regex = "1.3"
reqwest = { version = "0.10", features = [ "socks" ] }
serde = { version = "1.0", features = [ "derive" ] }
teloxide = "0.1"
toml = "0.5"
tokio = "0.2"
