[package]
name = "notify-tg"
version = "0.1.0"
authors = ["Mr-Andersen <andrew-anderson.neo@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
dirs = "2.0"
reqwest = "0.10"
serde = { version = "1.0", features = [ "derive" ] }
teloxide = "0.1"
toml = "0.5"
tokio = "0.2"
