[package]
name = "notify-tg"
version = "1.4.1"
authors = ["Mr-Andersen <andrew-anderson.neo@yandex.ru>"]
edition = "2018"

[features]
default = []
socks = ["reqwest/socks"]

[dependencies.teloxide-core]
git = "https://github.com/teloxide/teloxide-core"
# features = ["nightly"]

[dependencies]
argh = "0.1"
dirs = "2.0"
env_logger = "0.7"
log = "0.4"
reqwest = "0.10"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
tokio = "0.2"
