[package]
name = "notify-tg"
version = "1.3.1"
authors = ["Mr-Andersen <andrew-anderson.neo@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1"
dirs = "2.0"
env_logger = "0.7"
log = "0.4"
regex = "1.3"
reqwest = { version = "0.10", features = [ "socks" ] }
serde = { version = "1.0", features = [ "derive" ] }
teloxide-core = { git = "https://github.com/teloxide/teloxide-core" }
toml = "0.5"
tokio = "0.2"
